#!/usr/bin/env bash

module load miniconda/4.12.0
module load R/4.2.2


JOB_COUNT=$1

shift

mkdir -p slurm

snakemake -j ${JOB_COUNT} -c ${JOB_COUNT} \
    --nt --ri -k --max-jobs-per-second 2 -w 60 \
    --jobname "{rulename}.{jobid}"  \
    --latency-wait 60 \
    --cluster "srun -p compute --qos=batch {params.cluster_opts} --output=$(pwd)/slurm/%j.out " \
    --rerun-triggers=mtime \
    $@
