## This file is supposed to be bundled in the JAR file

# Maven will insert the project version here, e.g. 1.0.9
clintlr:
  version: @project.version@
  title: 'ClintLR: Clinical Intuition with Likelihood Ratios'

  # URL pointing to v2022-12-01 version of Monarch Disease Ontology JSON file.
  # We can replace the URL with permanent URL when the issue below is resolved.
  # https://github.com/monarch-initiative/phenol/issues/372
  mondo-json-url: http://purl.obolibrary.org/obo/mondo.json
  lirical:
    # TODO - consider using Jannovar files hosted at Zenodo, as listed here - https://github.com/charite/jannovar
    jannovar-hg19-ucsc-url: https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_ucsc.ser
    jannovar-hg19-refseq-url: https://storage.googleapis.com/ielis/jannovar/v0.35/hg19_refseq.ser
    jannovar-hg38-ucsc-url: https://storage.googleapis.com/ielis/jannovar/v0.35/hg38_ucsc.ser
    jannovar-hg38-refseq-url: https://storage.googleapis.com/ielis/jannovar/v0.35/hg38_refseq.ser
