# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build GUI JAR files

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macOS-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'

      - name: Install LIRICAL
        run: |
          cd ..
          git clone https://github.com/TheJacksonLaboratory/LIRICAL
          cd LIRICAL
          git checkout $LIRICAL_TAG
          ./mvnw --quiet -PskipTests -Prelease install

      - name: Build with Maven
        run: ./mvnw -PskipTests package
