name: Build GUI JARs

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - develop

env:
  # The LIRICAL tag to check out. The tag must correspond to the LIRICAL version used by ClintLR
  LIRICAL_TAG: v2.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: 21
          distribution: 'graalvm'

      - name: Install LIRICAL
        run: |
          cd ..
          git clone https://github.com/TheJacksonLaboratory/LIRICAL
          cd LIRICAL
          git checkout $LIRICAL_TAG
          ./mvnw --quiet -PskipTests -Prelease install

      - name: Build with Maven
        run: ./mvnw -PskipTests package

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: clintlr-gui-${{ matrix.os }}
          path: clintlr-gui/target/clintlr-gui-*.jar
          retention-days: 7
